create or replace procedure Structure_Re_Create ()
language plpgsql
as $$

begin

revoke execute on procedure instrument_insert from rl_manager;
revoke execute on procedure instrument_update from rl_manager;
revoke execute on procedure supplier_insert from rl_manager;
revoke execute on procedure supplier_update from rl_manager;
revoke execute on procedure supply_estimate_insert from rl_manager;
revoke execute on procedure supply_estimate_update from rl_manager;
revoke execute on procedure estimate_item_insert from rl_manager;
revoke execute on procedure estimate_item_update from rl_manager;
revoke execute on procedure estimate_item_delete from rl_manager;
revoke execute on procedure user_profile_update from rl_manager;

revoke execute on procedure instrument_update from rl_sales;
revoke execute on procedure purchase_order_insert from rl_sales;
revoke execute on procedure purchase_order_update from rl_sales;
revoke execute on procedure order_item_insert from rl_sales;
revoke execute on procedure order_item_update from rl_sales;
revoke execute on procedure order_item_delete from rl_sales;
revoke execute on procedure user_profile_update from rl_sales;

revoke execute on procedure supply_receipt_insert from rl_accountant;
revoke execute on procedure supply_receipt_update from rl_accountant;
revoke execute on procedure purchase_receipt_insert from rl_accountant;
revoke execute on procedure purchase_receipt_update from rl_accountant;

revoke execute on procedure instrument_type_insert from rl_admin;
revoke execute on procedure instrument_type_update from rl_admin;
revoke execute on procedure instrument_type_delete from rl_admin;
revoke execute on procedure country_insert from rl_admin;
revoke execute on procedure country_update from rl_admin;
revoke execute on procedure country_delete from rl_admin;
revoke execute on procedure material_insert from rl_admin;
revoke execute on procedure material_update from rl_admin;
revoke execute on procedure material_delete from rl_admin;
revoke execute on procedure post_insert from rl_admin;
revoke execute on procedure post_update from rl_admin;
revoke execute on procedure post_delete from rl_admin;
revoke execute on procedure status_insert from rl_admin;
revoke execute on procedure status_update from rl_admin;
revoke execute on procedure status_delete from rl_admin;
revoke execute on procedure user_profile_insert from rl_admin;
revoke execute on procedure user_profile_delete from rl_admin;
revoke execute on procedure employee_insert from rl_admin;
revoke execute on procedure employee_update from rl_admin;
revoke execute on procedure employee_delete from rl_admin;
revoke execute on procedure customer_insert from rl_admin;
revoke execute on procedure customer_update from rl_admin;
revoke execute on procedure customer_delete from rl_admin;
revoke execute on procedure supplier_delete from rl_admin;
revoke execute on procedure instrument_delete from rl_admin;
revoke execute on procedure supply_estimate_delete from rl_admin;
revoke execute on procedure supply_receipt_delete from rl_admin;
revoke execute on procedure purchase_order_delete from rl_admin;
revoke execute on procedure purchase_receipt_delete from rl_admin;

drop procedure if exists purchase_receipt_delete(p_id_purchase_receipt int);
drop procedure if exists purchase_receipt_update(p_id_purchase_receipt int, p_receipt_number varchar(25), p_id_purchase_order int, p_payment_type varchar(20), p_amount_paid decimal(12,2), p_change_amount decimal(10,2), p_employee_login varchar(36));
drop procedure if exists purchase_receipt_insert(p_receipt_number varchar(25), p_id_purchase_order int, p_payment_type varchar(20), p_amount_paid decimal(12,2), p_change_amount decimal(10,2), p_employee_login varchar(36));
drop procedure if exists order_item_delete(p_id_order_item int);
drop procedure if exists order_item_update(p_id_order_item int, p_id_purchase_order int, p_id_instrument int, p_quantity int, p_item_price decimal(10,2));
drop procedure if exists order_item_insert(p_id_purchase_order int, p_id_instrument int, p_quantity int, p_item_price decimal(10,2));
drop procedure if exists purchase_order_delete(p_id_purchase_order int);
drop procedure if exists purchase_order_update(p_id_purchase_order int, p_order_number varchar(20), p_customer_login varchar(36), p_id_status int, p_total_amount decimal(12,2));
drop procedure if exists purchase_order_insert(p_order_number varchar(20), p_customer_login varchar(36), p_id_status int, p_total_amount decimal(12,2));
drop procedure if exists supply_receipt_delete(p_id_supply_receipt int);
drop procedure if exists supply_receipt_update(p_id_supply_receipt int, p_receipt_number varchar(25), p_id_supply_estimate int, p_amount_paid decimal(12,2), p_employee_login varchar(36));
drop procedure if exists supply_receipt_insert(p_receipt_number varchar(25), p_id_supply_estimate int, p_amount_paid decimal(12,2), p_employee_login varchar(36));
drop procedure if exists estimate_item_delete(p_id_estimate_item int);
drop procedure if exists estimate_item_update(p_id_estimate_item int, p_id_supply_estimate int, p_id_instrument int, p_quantity int, p_item_price decimal(10,2));
drop procedure if exists estimate_item_insert(p_id_supply_estimate int, p_id_instrument int, p_quantity int, p_item_price decimal(10,2));
drop procedure if exists supply_estimate_delete(p_id_supply_estimate int);
drop procedure if exists supply_estimate_update(p_id_supply_estimate int, p_estimate_number varchar(15), p_id_supplier int, p_id_status int, p_total_amount decimal(12,2));
drop procedure if exists supply_estimate_insert(p_estimate_number varchar(15), p_id_supplier int, p_id_status int, p_total_amount decimal(12,2));
drop procedure if exists instrument_delete(p_id_instrument int);
drop procedure if exists instrument_update(p_id_instrument int, p_article varchar(15), p_id_instrument_type int, p_id_country int, p_brand_model varchar(100), p_frequency_range varchar(50), p_id_material int, p_quantity int, p_price decimal(10,2));
drop procedure if exists instrument_insert(p_article varchar(15), p_id_instrument_type int, p_id_country int, p_brand_model varchar(100), p_frequency_range varchar(50), p_id_material int, p_quantity int, p_price decimal(10,2));
drop procedure if exists supplier_delete(p_id_supplier int);
drop procedure if exists supplier_update(p_id_supplier int, p_full_name_supplier varchar(200), p_legal_address varchar(200), p_phone varchar(20), p_bik varchar(9), p_okpo varchar(20), p_responsible_login varchar(36));
drop procedure if exists supplier_insert(p_full_name_supplier varchar(200), p_legal_address varchar(200), p_phone varchar(20), p_bik varchar(9), p_okpo varchar(20), p_responsible_login varchar(36));
drop procedure if exists customer_delete(p_customer_login varchar(36));
drop procedure if exists customer_update(p_customer_login_old varchar(36), p_customer_login_new varchar(36), p_passport_data varchar(20), p_address varchar(200), p_phone varchar(20), p_bank_card varchar(25));
drop procedure if exists customer_insert(p_customer_login varchar(36), p_passport_data varchar(20), p_address varchar(200), p_phone varchar(20), p_bank_card varchar(25));
drop procedure if exists employee_delete(p_employee_login varchar(36));
drop procedure if exists employee_update(p_employee_login_old varchar(36), p_employee_login_new varchar(36), p_personal_file_n varchar(13));
drop procedure if exists employee_insert(p_employee_login varchar(36), p_personal_file_n varchar(13));
drop procedure if exists user_profile_delete(p_up_login varchar(36));
drop procedure if exists user_profile_update(p_up_login_old varchar(36), p_up_login_new varchar(36), p_up_password varchar(36), p_u_surname varchar(50), p_u_name varchar(50), p_u_patronymic varchar(50));
drop procedure if exists user_profile_insert(p_up_login varchar(36), p_up_password varchar(36), p_u_surname varchar(50), p_u_name varchar(50), p_u_patronymic varchar(50));
drop procedure if exists status_delete(p_id_status int);
drop procedure if exists status_update(p_id_status int, p_name_status varchar(50));
drop procedure if exists status_insert(p_name_status varchar(50));
drop procedure if exists post_delete(p_id_post int);
drop procedure if exists post_update(p_id_post int, p_name_post varchar(50));
drop procedure if exists post_insert(p_name_post varchar(50));
drop procedure if exists material_delete(p_id_material int);
drop procedure if exists material_update(p_id_material int, p_name_material varchar(100));
drop procedure if exists material_insert(p_name_material varchar(100));
drop procedure if exists country_delete(p_id_country int);
drop procedure if exists country_update(p_id_country int, p_name_country varchar(50));
drop procedure if exists country_insert(p_name_country varchar(50));
drop procedure if exists instrument_type_delete(p_id_instrument_type int);
drop procedure if exists instrument_type_update(p_id_instrument_type int, p_name_instrument_type varchar(50));
drop procedure if exists instrument_type_insert(p_name_instrument_type varchar(50));

revoke usage, select on sequence purchase_receipt_id_purchase_receipt_seq from rl_accountant;
revoke usage, select on sequence order_item_id_order_item_seq from rl_sales;
revoke usage, select on sequence purchase_order_id_purchase_order_seq from rl_sales;
revoke usage, select on sequence supply_receipt_id_supply_receipt_seq from rl_accountant;
revoke usage, select on sequence estimate_item_id_estimate_item_seq from rl_manager;
revoke usage, select on sequence supply_estimate_id_supply_estimate_seq from rl_manager;
revoke usage, select on sequence instrument_id_instrument_seq from rl_manager;
revoke usage, select on sequence supplier_id_supplier_seq from rl_manager;
revoke usage, select on sequence status_id_status_seq from rl_admin;
revoke usage, select on sequence post_id_post_seq from rl_admin;
revoke usage, select on sequence material_id_material_seq from rl_admin;
revoke usage, select on sequence country_id_country_seq from rl_admin;
revoke usage, select on sequence instrument_type_id_instrument_type_seq from rl_admin;

revoke select, insert, update on Instrument from rl_manager;
revoke select, insert, update on Supplier from rl_manager;
revoke select, insert, update on Supply_Estimate from rl_manager;
revoke select, insert, update, delete on Estimate_Item from rl_manager;
revoke select on Supply_Receipt from rl_manager;
revoke select on Status from rl_manager;
revoke select on Instrument_Type from rl_manager;
revoke select on Country from rl_manager;
revoke select on Material from rl_manager;
revoke select, update on User_Profile from rl_manager;

revoke select, update on Instrument from rl_sales;
revoke select, insert, update on Purchase_Order from rl_sales;
revoke select, insert, update, delete on Order_Item from rl_sales;
revoke select on Purchase_Receipt from rl_sales;
revoke select on Customer from rl_sales;
revoke select on Status from rl_sales;
revoke select on Instrument_Type from rl_sales;
revoke select on Country from rl_sales;
revoke select on Material from rl_sales;
revoke select, update on User_Profile from rl_sales;

revoke select on Instrument from rl_accountant;
revoke select on Supplier from rl_accountant;
revoke select on Supply_Estimate from rl_accountant;
revoke select on Estimate_Item from rl_accountant;
revoke select, insert, update on Supply_Receipt from rl_accountant;
revoke select on Purchase_Order from rl_accountant;
revoke select on Order_Item from rl_accountant;
revoke select, insert, update on Purchase_Receipt from rl_accountant;
revoke select on Customer from rl_accountant;
revoke select on Employee from rl_accountant;
revoke select on Status from rl_accountant;

revoke select, insert, update, delete on Instrument_Type from rl_admin;
revoke select, insert, update, delete on Country from rl_admin;
revoke select, insert, update, delete on Material from rl_admin;
revoke select, insert, update, delete on Post from rl_admin;
revoke select, insert, update, delete on Status from rl_admin;
revoke select, insert, update, delete on User_Profile from rl_admin;
revoke select, insert, update, delete on Employee from rl_admin;
revoke select, insert, update, delete on Customer from rl_admin;
revoke select, insert, update, delete on Supplier from rl_admin;
revoke select, insert, update, delete on Instrument from rl_admin;
revoke select, insert, update, delete on Supply_Estimate from rl_admin;
revoke select, insert, update, delete on Estimate_Item from rl_admin;
revoke select, insert, update, delete on Supply_Receipt from rl_admin;
revoke select, insert, update, delete on Purchase_Order from rl_admin;
revoke select, insert, update, delete on Order_Item from rl_admin;
revoke select, insert, update, delete on Purchase_Receipt from rl_admin;

drop index if exists index_ID_Purchase_Receipt;
drop index if exists index_Receipt_Number;
drop index if exists index_ID_Order_Item;
drop index if exists index_ID_Purchase_Order;
drop index if exists index_Order_Number;
drop index if exists index_ID_Supply_Receipt;
drop index if exists index_ID_Estimate_Item;
drop index if exists index_Create_DateTime;
drop index if exists index_Estimate_Number;
drop index if exists index_ID_Supply_Estimate;
drop index if exists index_Price;
drop index if exists index_Brand_Model;
drop index if exists index_Article;
drop index if exists index_ID_Instrument;
drop index if exists index_OKPO;
drop index if exists index_ID_Supplier;
drop index if exists index_Bank_Card;
drop index if exists index_Passport_Data;
drop index if exists index_Customer_Login;
drop index if exists index_Personal_File_N;
drop index if exists index_Employee_Login;
drop index if exists index_U_Surname_Name_Patronymic;
drop index if exists index_UP_Login_Password;
drop index if exists index_Name_Status;
drop index if exists index_ID_Status;
drop index if exists index_Name_Post;
drop index if exists index_ID_Post;
drop index if exists index_Name_Material;
drop index if exists index_ID_Material;
drop index if exists index_Name_Country;
drop index if exists index_ID_Country;
drop index if exists index_Name_Instrument_Type;
drop index if exists index_ID_Instrument_Type;

drop table if exists Purchase_Receipt;
drop table if exists Order_Item;
drop table if exists Purchase_Order;
drop table if exists Supply_Receipt;
drop table if exists Estimate_Item;
drop table if exists Supply_Estimate;
drop table if exists Instrument;
drop table if exists Supplier;
drop table if exists Customer;
drop table if exists Employee;
drop table if exists User_Profile;
drop table if exists Status;
drop table if exists Post;
drop table if exists Material;
drop table if exists Country;
drop table if exists Instrument_Type;

call Structure_Create();

end;

$$;